In [1]:
import torch

In [2]:
torch.manual_seed(42)

### Adam => AdamW

- Adam with decoupled weight decay (AdamW).

### Grad Clip & Grad Norm

- gradient clipping，梯度裁剪，一般用于解决 梯度爆炸 (gradient explosion) 问题
- grad norm
  - if $\|\textbf g\|\geq c$，则有 $\textbf g\leftarrow c\frac{\textbf g}{\|\textbf g\|}$

```
# Define the maximum gradient norm threshold
max_grad_norm = 1.0

# Training loop
for epoch in range(num_epochs):
    for inputs, targets in dataloader: # Replace dataloader with your data loading me
        optimizer.zero_grad() # Zero the gradients

        # Forward pass
        outputs = model(inputs)
        loss = criterion(outputs, targets)

        # Backward pass
        loss.backward()

        # Apply gradient clipping to prevent exploding gradientS
        nn.utils.clip_grad_norm_(model.parameters(), max_grad_norm)

        # Update weights
        optimizer.step()
        # Perform other training loop operations (e.g., validation)

```

In [3]:
w = torch.rand(5) * 1000
w_1 = w.clone()
w.requires_grad_(True)
w_1.requires_grad_(True)
loss = 1/2 * torch.sum(w_1 * w_1 + w * w)
# Here grads of loss w.r.t w and w_1 should be w and w_1 respectively
loss.backward()

In [4]:
# Clip grads of w_1
torch.nn.utils.clip_grad_norm_(w_1, max_norm=1.0, norm_type=2)

tensor(1683.7260)

In [7]:
torch.norm(w_1, p=2)

tensor(1683.7260, grad_fn=<LinalgVectorNormBackward0>)

In [8]:
w.grad

tensor([882.2693, 915.0040, 382.8638, 959.3057, 390.4482])

In [9]:
w_1.grad

tensor([0.5240, 0.5434, 0.2274, 0.5698, 0.2319])

In [10]:
torch.norm(w_1.grad, p=2) 

tensor(1.)

In [11]:
w.grad / torch.norm(w.grad, p=2)

tensor([0.5240, 0.5434, 0.2274, 0.5698, 0.2319])